apiVersion: v1
kind: Service
metadata:
  name: {{ include "stump.fullname" . }}
  namespace: {{ include  "stump.namespace" . }}
  labels:
    {{- include "stump.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}

  selector:
    {{- include "stump.selectorLabels" . | nindent 4 }}

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

  {{- with .Values.service.clusterIP }}
  clusterIP: {{ . | quote }}
  {{- end }}

  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}

  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
