apiVersion: v2
name: stump
kubeVersion: ">=1.25.0-0"
description: A Helm chart for Stump, a free and open source comics, manga and digital book server with OPDS support
sources:
  - https://github.com/stumpapp/stump
home: https://stumpapp.dev
icon: https://github.com/stumpapp/stump/raw/main/.github/images/logo.png
keywords:
  - stump
  - comics
  - manga
  - books
  - opds
  - media
  - self-hosted
type: application
version: 0.2.0
appVersion: "0.1.10"