apiVersion: v2
name: calibre-web-automated
description: Helm chart for Calibre-Web-Automated
type: application

version: 0.1.1
appVersion: "dev-429"

home: https://github.com/crocodilestick/Calibre-Web-Automated
sources:
  - https://github.com/crocodilestick/Calibre-Web-Automated

keywords:
  - calibre
  - calibre-web
  - ebooks
  - library
  - books
